kakao-tech-campus-2nd-step3/Team3_BE

src/main/java/com/splanet/splanet/Comment/entity/Comment.java, src/main/java/com/splanet/splanet/Comment/repository/CommentRepository.java, src/main/java/com/splanet/splanet/Friend/entity/Friend.java, src/main/java/com/splanet/splanet/Friend/repository/FriendRepository.java, src/main/java/com/splanet/splanet/FriendRequest/entity/FriendRequest.java, src/main/java/com/splanet/splanet/FriendRequest/repository/FriendRequestRepository.java, src/main/java/com/splanet/splanet/Payment/entity/Payment.java, src/main/java/com/splanet/splanet/Payment/repository/PaymentRepository.java, src/main/java/com/splanet/splanet/Subscription/entity/Subscription.java, src/main/java/com/splanet/splanet/Subscription/repository/SubscriptionRepository.java
> Comment, Friend, FriendRequest, Payment, Subscription 엔티티 및 레포지토리 작성
=> [feature]: Comment, Friend, FriendRequest, Payment, Subscription 엔티티 및 레포지토리 작성

src/main/java/com/splanet/splanet/core/exception/BusinessException.java, src/main/java/com/splanet/splanet/core/exception/ErrorCode.java, src/main/java/com/splanet/splanet/core/exception/ErrorResponse.java, src/main/java/com/splanet/splanet/core/exception/GlobalExceptionHandler.java
> 추후 원활한 협업을 위해 에러 핸들링을 위한 기초 틀을 잡는다.
close #7
=> [feature]: 에러 핸들링 틀 생성

src/main/java/com/splanet/splanet/comment/entity/Comment.java, src/main/java/com/splanet/splanet/comment/repository/CommentRepository.java, src/main/java/com/splanet/splanet/friend/entity/Friend.java, src/main/java/com/splanet/splanet/friend/repository/FriendRepository.java, src/main/java/com/splanet/splanet/friendRequest/entity/FriendRequest.java, src/main/java/com/splanet/splanet/friendRequest/repository/FriendRequestRepository.java, src/main/java/com/splanet/splanet/payment/entity/Payment.java, src/main/java/com/splanet/splanet/payment/repository/PaymentRepository.java, src/main/java/com/splanet/splanet/plan/entity/Plan.java, src/main/java/com/splanet/splanet/plan/entity/TeamPlan.java, src/main/java/com/splanet/splanet/subscription/entity/Subscription.java, src/main/java/com/splanet/splanet/subscription/repository/SubscriptionRepository.java, src/main/java/com/splanet/splanet/team/entity/Team.java, src/main/java/com/splanet/splanet/user/entity/User.java
> 3주차 코드 피드백 받은 부분 반영하여 리팩토링
close #18
=> [refactor]: 3주차 피드백 반영

build.gradle, src/main/java/com/splanet/splanet/core/exception/ErrorCode.java, src/main/java/com/splanet/splanet/core/exception/GlobalExceptionHandler.java, src/main/java/com/splanet/splanet/plan/controller/PlanController.java, src/main/java/com/splanet/splanet/plan/dto/PlanRequestDto.java, src/main/java/com/splanet/splanet/plan/dto/PlanResponseDto.java, src/main/java/com/splanet/splanet/plan/entity/Plan.java, src/main/java/com/splanet/splanet/plan/mapper/PlanMapper.java, src/main/java/com/splanet/splanet/plan/repository/PlanRepository.java, src/main/java/com/splanet/splanet/plan/service/PlanService.java, src/test/java/com/splanet/splanet/plan/entity/PlanTest.java, src/test/java/com/splanet/splanet/plan/service/PlanServiceTest.java, src/test/java/com/splanet/splanet/user/service/UserServiceTest.java
> Plan 생성, 조회, 수정, 삭제 API를 구현한다.
커밋을 잘못찍어서 user api 라고 작성했습니다................................ 조심하겠습니다 괜히 수정하다가 꼬일 것 같아 그대로 둡니다
close #30
=> [feature]: Plan API 구현

src/main/java/com/splanet/splanet/core/exception/ErrorCode.java, src/main/java/com/splanet/splanet/core/exception/GlobalExceptionHandler.java, src/main/java/com/splanet/splanet/oauth/JwtAuthenticationFilter.java, src/main/java/com/splanet/splanet/oauth/OAuth2AuthenticationSuccessHandler.java, src/main/java/com/splanet/splanet/oauth/TokenController.java, src/main/java/com/splanet/splanet/user/controller/UserController.java, src/main/java/com/splanet/splanet/user/entity/User.java, src/main/java/com/splanet/splanet/user/repository/UserRepository.java, src/main/java/com/splanet/splanet/user/service/UserService.java
> 유저에 관한 취약점을 보완한다.
테스트 유저 생성 후 token 컨트롤러에서 토큰을 발급받으면 해당 유저로 로그인 가능합니다.
close #36
=> [bug]: 유저 관련 취약점 보완

src/main/java/com/splanet/splanet/comment/controller/CommentController.java, src/main/java/com/splanet/splanet/comment/dto/CommentRequest.java, src/main/java/com/splanet/splanet/comment/dto/CommentResponse.java, src/main/java/com/splanet/splanet/comment/entity/Comment.java, src/main/java/com/splanet/splanet/comment/repository/CommentRepository.java, src/main/java/com/splanet/splanet/comment/service/CommentService.java, src/main/java/com/splanet/splanet/core/exception/ErrorCode.java, src/test/java/com/splanet/splanet/comment/entity/CommentTest.java, src/test/java/com/splanet/splanet/comment/service/CommentServiceTest.java
> 댓글 api 구현하고 테스트 작성
충돌 발생
close #33
=> [feature]: Comments CRUD 구현

src/main/java/com/splanet/splanet/comment/controller/CommentApi.java, src/main/java/com/splanet/splanet/comment/controller/CommentController.java, src/main/java/com/splanet/splanet/comment/dto/CommentRequest.java, src/main/java/com/splanet/splanet/comment/dto/CommentResponse.java, src/main/java/com/splanet/splanet/comment/service/CommentService.java, src/main/java/com/splanet/splanet/core/exception/ErrorCode.java, src/main/java/com/splanet/splanet/payment/service/PaymentService.java, src/main/java/com/splanet/splanet/subscription/service/SubscriptionService.java, src/test/java/com/splanet/splanet/comment/service/CommentServiceTest.java
> 멘토님이 5주차 리뷰해주신 부분(댓글 api) 수정했습니다.
강욱님이 API 인터페이스 만들어주셨는데 제가 따로 컨트롤러 수정하다가 충돌발생 한 것 같아요 제꺼는 덮고 충돌 잡아주시면 될 것 같습니다!
close #47
=> [refactor]: 5주차 코드리뷰 반영하여 수정

.github/workflows/ci.yml, src/main/java/com/splanet/splanet/jwt/JwtTokenProvider.java
>  CI 워크플로우 작성
PR 올리면 워크플로우 돌아갑니다.
성공하면 이렇게 뜹니다. 실패하면 X 뜨니까 테스트코드나 빌드가 제대로 되나 확인해주세요
실패하면 테스트 실패하거나 빌드가 안되는겁니다. 코드 수정하세요
close #64
=> [feature]: CI 워크플로우 작성

src/main/java/com/splanet/splanet/previewplan/entity/PlanCard.java, src/main/java/com/splanet/splanet/previewplan/entity/PlanGroup.java, src/main/java/com/splanet/splanet/previewplan/entity/PreviewPlan.java, src/main/java/com/splanet/splanet/previewplan/service/PreviewPlanService.java
> TTL이 제대로 설정되어있지 않던 문제를 수정한다.
close #66
=> [feat]: previewPlan TTL을 제대로 적용하지 않은 문제 수정

.github/workflows/cd.yml, .github/workflows/ci.yml
> 빌드 캐싱 및 트리거 수정, 전체적인 코드 수정
https://kanguk-room.notion.site/CI-CD-129036cad7a880e0bd7edc63590af94d?pvs=4
close #75
=> [refactor]: CI/CD 수정

.github/workflows/cd.yml, src/main/java/com/splanet/splanet/config/SwaggerConfig.java, src/main/resources/application-prod.yml
> 서브도메인 적용 후 문제가 된 부분 수정
close #이슈번호
=> [refactor]: 배포 후 문제되는 부분 수정

.github/workflows/ci.yml, build.gradle, src/main/java/com/splanet/splanet/comment/service/CommentService.java, src/test/java/com/splanet/splanet/SplanetApplicationTests.java, src/test/java/com/splanet/splanet/user/controller/UserControllerAcceptanceTest.java, src/test/java/com/splanet/splanet/user/controller/UserControllerIntegrationTest.java, src/test/resources/application-test.yml, src/test/resources/application.yml
> 테스트 이슈 해결 및 User 통합테스트, 인수테스트 작성
제 코드 참고해서 통합테스트 작성해주시면 됩니다.
close #90
=> [test]: 테스트 이슈 해결 및 User 통합테스트, 인수테스트 작성

.github/workflows/cd.yml, src/main/java/com/splanet/splanet/config/SwaggerConfig.java
> Blue/Green 무중단 배포 구현
https://github.com/user-attachments/assets/c109d9c0-5e69-4160-bf65-88639f87bb8e
close #96
=> [feat]: Blue/Green 무중단 배포

src/main/java/com/splanet/splanet/team/dto/TeamMemberDto.java, src/main/java/com/splanet/splanet/team/service/TeamService.java
팀 멤버 조회시 팀 멤버 권한 조회 추가
> 작업 내용을 요약하여 설명해주세요
close #105
=> feat: 팀 멤버 조회시 팀 멤버 권한 조회 추가

src/main/java/com/splanet/splanet/gpt/service/GptPlanSaveService.java
> timestamp 형식도 Redis 에 바로 저장되도록 수정
close #이슈번호
=> [bug]: timestamp 형식도 Redis 에 바로 저장되도록 수정

src/main/java/com/splanet/splanet/core/exception/ErrorCode.java, src/main/java/com/splanet/splanet/previewplan/dto/PlanCardResponseDto.java, src/test/java/com/splanet/splanet/previewplan/service/PreviewPlanServiceTest.java
> 시간 표현 형식때문에 수정, 조회가 제대로 안되는 오류
close #115
=> [fix]: 시간 표현 형식때문에 수정, 조회가 제대로 안되는 오류

build.gradle, docker-compose-aws.yml, docker-compose.yml, prometheus/prometheus.yml, src/main/resources/application-local.yml, src/main/resources/application.yml
=> feat: 모니터링 yml에 추가

src/main/java/com/splanet/splanet/core/exception/ErrorCode.java, src/main/java/com/splanet/splanet/team/repository/TeamInvitationRepository.java, src/main/java/com/splanet/splanet/team/service/TeamService.java, src/test/java/com/splanet/splanet/team/service/TeamServiceTest.java
=> fix: 초대 여러번 되는 버그 수정

src/main/java/com/splanet/splanet/config/SecurityConfig.java
=> [bug]: CORS 해결

src/main/resources/application.yml
>  health check가 안되던 문제 해결
다시 된다.
close #125
=> [bug]: health check가 안되던 문제 해결

src/main/java/com/splanet/splanet/core/exception/GlobalExceptionHandler.java, src/main/java/com/splanet/splanet/plan/service/PlanService.java, src/main/java/com/splanet/splanet/teamplan/service/TeamPlanService.java, src/test/java/com/splanet/splanet/plan/controller/PlanControllerAcceptanceTest.java, src/test/java/com/splanet/splanet/plan/controller/PlanControllerIntegrationTest.java, src/test/java/com/splanet/splanet/plan/service/PlanServiceTest.java
>  Plan 통합, 인수 테스트 추가
close #이슈번호
=> [test]: Plan 통합, 인수 테스트 추가

.github/workflows/cd.yml, .github/workflows/rollback.yml
>  CD 파이프라인 보완 (에러 처리 및 롤백 로직)
close #이슈번호
=> [refactor]: CD 파이프라인 보완 (에러 처리 및 롤백 로직)

Dockerfile
=> refactor: 도커 파일 수정

src/main/java/com/splanet/splanet/core/properties/OAuth2Properties.java, src/main/java/com/splanet/splanet/gpt/controller/GptController.java, src/main/java/com/splanet/splanet/gpt/service/GptService.java, src/main/java/com/splanet/splanet/oauth/OAuth2AuthenticationSuccessHandler.java, src/main/resources/application-local.yml, src/main/resources/application-prod.yml
> 요청 환경에 따라 로그인 리다이렉트 다르게, GptService 리팩토링
close #146
=> [refactor]: 11주차 피드백 반영

src/main/java/com/splanet/splanet/oauth/OAuth2AuthenticationSuccessHandler.java, src/main/resources/application-local.yml, src/main/resources/application-prod.yml
> host 헤더 검사 후 각 환경에 맞게 리다이렉트 하도록 수정
close #이슈번호
=> [refactor]: 요청 환경에 따라서 리다이렉트를 다르게 처리하도록 수정

src/main/java/com/splanet/splanet/oauth/OAuth2AuthenticationSuccessHandler.java
> 이전에 작업한 내용이 제대로 작동하지 않아 다시 작업 (로그인 환경따라 다르게 처리)
close #146
=> [refactor]: 로그인 환경에 따라 다르게 처리 수정

src/main/java/com/splanet/splanet/core/exception/GlobalExceptionHandler.java
=> [refactor]: 에러메시지 NULL 처리

src/main/java/com/splanet/splanet/log/interceptor/ApiLoggingInterceptor.java, src/main/java/com/splanet/splanet/log/service/LogService.java, src/main/java/com/splanet/splanet/oauth/OAuth2AuthenticationSuccessHandler.java, src/test/java/com/splanet/splanet/log/service/LogServiceTest.java
=> refactor: 상태코드 남기기

.github/workflows/cd.yml, .gitignore, src/main/java/com/splanet/splanet/core/exception/ErrorCode.java, src/main/java/com/splanet/splanet/gpt/service/GptService.java, src/main/java/com/splanet/splanet/notification/controller/FcmTokenApi.java, src/main/java/com/splanet/splanet/notification/controller/FcmTokenController.java, src/main/java/com/splanet/splanet/notification/repository/FcmTokenRepository.java, src/main/java/com/splanet/splanet/notification/service/FcmTokenService.java, src/main/java/com/splanet/splanet/notification/service/NotificationService.java, src/main/java/com/splanet/splanet/plan/dto/PlanResponseDto.java, src/main/java/com/splanet/splanet/plan/dto/PlanTimeDto.java, src/main/java/com/splanet/splanet/plan/repository/PlanRepository.java, src/main/java/com/splanet/splanet/plan/service/PlanService.java, src/test/java/com/splanet/splanet/notification/service/FcmTokenServiceTest.java
> FCM 토큰 로직 수정 및 GPT api 보완
close #166
=> [refactor]: FCM 토큰 로직 수정 및 GPT api 보완

src/main/java/com/splanet/splanet/team/repository/TeamInvitationRepository.java, src/main/java/com/splanet/splanet/team/repository/TeamUserRelationRepository.java, src/main/java/com/splanet/splanet/team/service/TeamService.java, src/test/java/com/splanet/splanet/team/service/TeamServiceTest.java
=> [bug]: 팀 삭제 버그 수정

.github/workflows/ci.yml, build.gradle
> 코드 커버리지를 CI 과정에서 자동 측정하도록 한다. 
close #이슈번호
=> [feat]: 코드 커버리지 측정 자동화

src/main/java/com/splanet/splanet/core/exception/GlobalExceptionHandler.java, src/main/java/com/splanet/splanet/log/interceptor/ApiLoggingInterceptor.java, src/main/java/com/splanet/splanet/oauth/OAuth2AuthenticationSuccessHandler.java
=> bug: 로깅 로직관련 버그 해결

src/main/java/com/splanet/splanet/core/exception/GlobalExceptionHandler.java
=> refactor: error log 이상 해결
